####  1. 三层简单神经网络

In [1]:
import tensorflow as tf

1.1 定义变量

In [16]:
w1= tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2= tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))
x = tf.constant([[0.7, 0.9]])

with tf.Session() as sess:
    #运行变量的initializer。调用op之前，所有变量都应被显式地初始化过。
    sess.run(w1.initializer)
    sess.run(w2.initializer)
    
    #查看值
    print (w1.eval())
    print (w2.eval())

[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
[[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]


1.2 定义前向传播的神经网络

In [20]:
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

with tf.Session() as sess:
    #运行变量的initializer。调用op之前，所有变量都应被显式地初始化过。
    sess.run(w1.initializer)
    sess.run(w2.initializer)
    
    #查看值
    print(sess.run(a))
    print(sess.run(y))

[[-2.7663565   1.1285427   0.57783246]]
[[3.957578]]


1.3 调用会话输出结果

In [18]:
sess = tf.Session()
sess.run(w1.initializer)  
sess.run(w2.initializer)  
print(sess.run(y))
sess.close()

[[3.957578]]


#### 2. 使用placeholder

In [36]:
x = tf.placeholder(tf.float32, shape=(1, 2), name="input")
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

with tf.Session().as_default() as sess:
    init_op = tf.global_variables_initializer()
    print(sess.run(init_op))
    print(sess.run(y, feed_dict={x: [[0.7, 0.9]]}))
    print(y.eval(feed_dict={x: [[.7,.9]]}))

None
[[ 3.95757794]]
[[ 3.95757794]]


#### 3. 增加多个输入

In [37]:
x = tf.placeholder(tf.float32, shape=(3, 2), name="input")
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

sess = tf.Session()
#使用tf.global_variables_initializer()来初始化所有的变量
init_op = tf.global_variables_initializer()  
sess.run(init_op)

print(sess.run(y, feed_dict={x: [[0.7,0.9],[0.1,0.4],[0.5,0.8]]})) 

[[ 3.95757794]
 [ 1.15376544]
 [ 3.16749239]]
