In [1]:
import tensorflow as tf
from numpy.random import RandomState

#### 1. 定义神经网络的参数，输入和输出节点。

In [2]:
batch_size = 8
dataset_size = 128
w1= tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1), trainable=True)
w2= tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1), trainable=True)
x = tf.placeholder(tf.float32, shape=(None, 2), name="x-input")
y_= tf.placeholder(tf.float32, shape=(None, 1), name='y-input')

#### 2. 定义前向传播过程，损失函数及反向传播算法。

In [3]:
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)
cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0))) 
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

####  3. 生成模拟数据集。

In [11]:
rdm = RandomState(1)
X = rdm.rand(dataset_size, 2)
Y = [[int(x1+x2 < 1)] for (x1, x2) in X]
Z = [[x1+x2] for (x1, x2) in X]

print (X,Z)
print (Y)
print (X.shape, type(X))
# dir(X)

[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01]
 [4.19194514e-01 6.85219500e-01]
 [2.04452250e-01 8.78117436e-01]
 [2.73875932e-02 6.70467510e-01]
 [4.17304802e-01 5.58689828e-01]
 [1.40386939e-01 1.98101489e-01]
 [8.00744569e-01 9.68261576e-01]
 [3.13424178e-01 6.92322616e-01]
 [8.76389152e-01 8.94606664e-01]
 [8.50442114e-02 3.90547832e-02]
 [1.69830420e-01 8.78142503e-01]
 [9.83468338e-02 4.21107625e-01]
 [9.57889530e-01 5.33165285e-01]
 [6.91877114e-01 3.15515631e-01]
 [6.86500928e-01 8.34625672e-01]
 [1.82882773e-02 7.50144315e-01]
 [9.88861089e-01 7.48165654e-01]
 [2.80443992e-01 7.89279328e-01]
 [1.03226007e-01 4.47893526e-01]
 [9.08595503e-01 2.93614148e-01]
 [2.87775339e-01 1.30028572e-01]
 [1.93669579e-02 6.78835533e-01]
 [2.11628116e-01 2.65546659e-01]
 [4.91573159e-01 5.33625451e-02]
 [5.74117605e-01 1.46728575e-01]
 [5.89305537e-01 6.99758360e-01]
 [1.023344

#### 4. 创建一个会话来运行TensorFlow程序。

In [16]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    
    # 输出目前（未经训练）的参数取值。
    print("w1:", sess.run(w1))
    print("w2:", sess.run(w2))
    print("\n")
    
    # 训练模型。
    STEPS = 10000
    for i in range(STEPS):
        start = (i*batch_size) % dataset_size
        end = (i*batch_size) % dataset_size + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            total_cross_entropy = sess.run(cross_entropy, feed_dict={x: X, y_: Y})
            print("After %d training step(s), cross entropy on all data is %g" % (i, total_cross_entropy))
            print("w1:", sess.run(w1))
            print("w2:", sess.run(w2))    
    # 输出训练后的参数取值。
#     print("\n")


w1: [[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
w2: [[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]


After 0 training step(s), cross entropy on all data is 0.0674925
w1: [[-0.8123182   1.4855988   0.06632921]
 [-2.4437041   0.1002484   0.59222424]]
w2: [[-0.8123182 ]
 [ 1.4855988 ]
 [ 0.06632937]]
After 1000 training step(s), cross entropy on all data is 0.0163385
w1: [[-1.2754937   1.9323932   0.71818316]
 [-2.827644    0.4706616   1.1418985 ]]
w2: [[-1.2119861]
 [ 1.9595636]
 [ 0.5508197]]
After 2000 training step(s), cross entropy on all data is 0.00907547
w1: [[-1.5139762  2.1591146  1.0742905]
 [-3.0170891  0.6484542  1.46365  ]]
w2: [[-1.4050641 ]
 [ 2.2063437 ]
 [ 0.83948904]]
After 3000 training step(s), cross entropy on all data is 0.00714436
w1: [[-1.6539443  2.292184   1.2743924]
 [-3.1415606  0.7646775  1.6682038]]
w2: [[-1.5261348]
 [ 2.3539424]
 [ 1.019857 ]]
After 4000 training step(s), cross entropy on all data is 0.00578471
w1: [[-1.79